name: rootfs

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  workflow_call:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{github.repository_owner}}/openeuler_wsl_rootfs


jobs:
  build-rootfs:
    name: Build openEuler ${{ matrix.release }} ${{ matrix.arch }} WSL rootfs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        release: [22.03, 20.03]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and save ${{ matrix.arch }} image
        id: build-and-push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: docker/
          platforms: linux/${{ matrix.arch }}
          tags: openeuler-wsl:${{ matrix.release }}
          build-args: REL_TAG=${{ matrix.release }}
          load: true

      - name: build wsl install.tar.gz
        id: build-rootfs
        run: |
          sh generate_rootfs.sh ${{ matrix.release }}
          mv install.tar.gz openeuler-${{ matrix.release }}-${{ matrix.arch }}-wsl-rootfs.tar.gz
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: openeuler-${{ matrix.release }}-${{ matrix.arch }}-wsl-rootfs.tar
          path: openeuler-${{ matrix.release }}-${{ matrix.arch }}-wsl-rootfs.tar.gz
